<?php


namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SubcountiesTableSeeder extends Seeder
{
    public function run(): void
    {
        $subcounties = [
            ["name" => "MOMBASA", "county_id" => 1],
            ["name" => "KISAUNI", "county_id" => 1],
            ["name" => "CHANGAMWE", "county_id" => 1],
            ["name" => "LIKONI", "county_id" => 1],
            ["name" => "NYALI", "county_id" => 1],
            ["name" => "JOMVU", "county_id" => 1],
            ["name" => "MATUGA", "county_id" => 2],
            ["name" => "MSAMBWENI", "county_id" => 2],
            ["name" => "KINANGO", "county_id" => 2],
            ["name" => "LUNGALUNGA", "county_id" => 2],
            ["name" => "KILIFI NORTH", "county_id" => 3],
            ["name" => "MALINDI", "county_id" => 3],
            ["name" => "MAGARINI", "county_id" => 3],
            ["name" => "KALOLENI", "county_id" => 3],
            ["name" => "RABAI", "county_id" => 3],
            ["name" => "GANZE", "county_id" => 3],
            ["name" => "KILIFI SOUTH", "county_id" => 3],
            ["name" => "TANA RIVER", "county_id" => 4],
            ["name" => "TANA NORTH", "county_id" => 4],
            ["name" => "TANA DELTA", "county_id" => 4],
            ["name" => "LAMU WEST", "county_id" => 5],
            ["name" => "LAMU EAST", "county_id" => 5],
            ["name" => "TAITA", "county_id" => 6],
            ["name" => "VOI", "county_id" => 6],
            ["name" => "TAVETA", "county_id" => 6],
            ["name" => "MWATATE", "county_id" => 6],
            ["name" => "GARISSA", "county_id" => 7],
            ["name" => "IJARA", "county_id" => 7],
            ["name" => "BALAMBALA", "county_id" => 7],
            ["name" => "FAFI", "county_id" => 7],
            ["name" => "HULUGHO", "county_id" => 7],
            ["name" => "LAGDERA", "county_id" => 7],
            ["name" => "DADAAB", "county_id" => 7],
            ["name" => "WAJIR EAST", "county_id" => 8],
            ["name" => "WAJIR NORTH", "county_id" => 8],
            ["name" => "TARBAJ", "county_id" => 8],
            ["name" => "BUNA", "county_id" => 8],
            ["name" => "WAJIR WEST", "county_id" => 8],
            ["name" => "ELDAS", "county_id" => 8],
            ["name" => "WAJIR SOUTH", "county_id" => 8],
            ["name" => "HABASWEIN", "county_id" => 8],
            ["name" => "MANDERA EAST", "county_id" => 9],
            ["name" => "MANDERA CENTRAL", "county_id" => 9],
            ["name" => "KOTULO", "county_id" => 9],
            ["name" => "MANDERA CENTRAL", "county_id" => 9],
            ["name" => "MANDERA NORTH", "county_id" => 9],
            ["name" => "MANDERA WEST", "county_id" => 9],
            ["name" => "LAFEY", "county_id" => 9],
            ["name" => "BANISA", "county_id" => 9],
            ["name" => "MARSABIT CENTRAL", "county_id" => 10],
            ["name" => "NORTH HORR", "county_id" => 10],
            ["name" => "MARSABIT NORTH", "county_id" => 10],
            ["name" => "MARSABIT SOUTH/LAISAMIS", "county_id" => 10],
            ["name" => "LOIYANGALANI", "county_id" => 10],
            ["name" => "MOYALE", "county_id" => 10],
            ["name" => "SOLOLO", "county_id" => 10],
            ["name" => "ISIOLO", "county_id" => 11],
            ["name" => "GARBATULLA", "county_id" => 11],
            ["name" => "MERTI", "county_id" => 11],
            ["name" => "BUURI", "county_id" => 12],
            ["name" => "MERU CENTRAL", "county_id" => 12],
            ["name" => "IMENTI NORTH", "county_id" => 12],
            ["name" => "IMENTI SOUTH", "county_id" => 12],
            ["name" => "TIGANIA WEST", "county_id" => 12],
            ["name" => "IGEMBE NORTH", "county_id" => 12],
            ["name" => "TIGANIA EAST", "county_id" => 12],
            ["name" => "IGEMBE SOUTH", "county_id" => 12],
            ["name" => "TIGANIA CENTRAL", "county_id" => 12],
            ["name" => "IGEMBE CENTRAL", "county_id" => 12],
            ["name" => "THARAKA NORTH", "county_id" => 13],
            ["name" => "THARAKA SOUTH", "county_id" => 13],
            ["name" => "MERU SOUTH", "county_id" => 13],
            ["name" => "MAARA", "county_id" => 13],
            ["name" => "EMBU WEST", "county_id" => 14],
            ["name" => "EMBU EAST", "county_id" => 14],
            ["name" => "EMBU NORTH", "county_id" => 14],
            ["name" => "MBEERE NORTH", "county_id" => 14],
            ["name" => "MBEERE SOUTH", "county_id" => 14],
            ["name" => "KITUI CENTRAL", "county_id" => 15],
            ["name" => "MWINGI CENTRAL", "county_id" => 15],
            ["name" => "KATULANI", "county_id" => 15],
            ["name" => "KITUI WEST", "county_id" => 15],
            ["name" => "MUTITU", "county_id" => 15],
            ["name" => "KISASI", "county_id" => 15],
            ["name" => "MATINYANI", "county_id" => 15],
            ["name" => "LOWER YATTA", "county_id" => 15],
            ["name" => "MUTOMO", "county_id" => 15],
            ["name" => "IKUTHA", "county_id" => 15],
            ["name" => "NZAMBANI", "county_id" => 15],
            ["name" => "MIGWANI/MWINGI WEST", "county_id" => 15],
            ["name" => "TSEIKURU", "county_id" => 15],
            ["name" => "KYUSO", "county_id" => 15],
            ["name" => "MUMONI", "county_id" => 15],
            ["name" => "MWINGI EAST", "county_id" => 15],
            ["name" => "MACHAKOS", "county_id" => 16],
            ["name" => "KANGUNDO", "county_id" => 16],
            ["name" => "MWALA", "county_id" => 16],
            ["name" => "YATTA", "county_id" => 16],
            ["name" => "MATUNGULU", "county_id" => 16],
            ["name" => "MASINGA", "county_id" => 16],
            ["name" => "KATHIANI", "county_id" => 16],
            ["name" => "ATHI RIVER", "county_id" => 16],
            ["name" => "MAKUENI", "county_id" => 17],
            ["name" => "KIBWEZI", "county_id" => 17],
            ["name" => "MAKINDU", "county_id" => 17],
            ["name" => "KILUNGU", "county_id" => 17],
            ["name" => "KATHONZWENI", "county_id" => 17],
            ["name" => "NZAUI", "county_id" => 17],
            ["name" => "MUKAA", "county_id" => 17],
            ["name" => "MBOONI WEST", "county_id" => 17],
            ["name" => "MBOONI EAST", "county_id" => 17],
            ["name" => "NYANDARUA NORTH", "county_id" => 18],
            ["name" => "NYANDARUA CENTRAL", "county_id" => 18],
            ["name" => "KIPIPIRI", "county_id" => 18],
            ["name" => "KINANGOP", "county_id" => 18],
            ["name" => "NYANDARUA SOUTH", "county_id" => 18],
            ["name" => "NYANDARUA WEST", "county_id" => 18],
            ["name" => "MIRANGINE", "county_id" => 18],
            ["name" => "NYERI CENTRAL", "county_id" => 19],
            ["name" => "KIENI EAST", "county_id" => 19],
            ["name" => "KIENI WEST", "county_id" => 19],
            ["name" => "TETU", "county_id" => 19],
            ["name" => "NYERI SOUTH", "county_id" => 19],
            ["name" => "MATHIRA EAST", "county_id" => 19],
            ["name" => "MATHIRA WEST", "county_id" => 19],
            ["name" => "MUKURWEINI", "county_id" => 19],
            ["name" => "KIRINYAGA CENTRAL", "county_id" => 20],
            ["name" => "KIRINYAGA EAST", "county_id" => 20],
            ["name" => "KIRINYAGA WEST", "county_id" => 20],
            ["name" => "MWEA EAST", "county_id" => 20],
            ["name" => "MWEA WEST", "county_id" => 20],
            ["name" => "MATHIOYA", "county_id" => 21],
            ["name" => "KANDARA", "county_id" => 21],
            ["name" => "KIGUMO", "county_id" => 21],
            ["name" => "KANGEMA", "county_id" => 21],
            ["name" => "KAHURO", "county_id" => 21],
            ["name" => "GATANGA", "county_id" => 21],
            ["name" => "KIAMBU", "county_id" => 22],
            ["name" => "LIMURU", "county_id" => 22],
            ["name" => "LARI", "county_id" => 22],
            ["name" => "GITHUNGURI", "county_id" => 22],
            ["name" => "GATUNDU NORTH", "county_id" => 22],
            ["name" => "THIKA WEST", "county_id" => 22],
            ["name" => "THIKA EAST", "county_id" => 22],
            ["name" => "RUIRU", "county_id" => 22],
            ["name" => "KIKUYU", "county_id" => 22],
            ["name" => "GATUNDU SOUTH", "county_id" => 22],
            ["name" => "KIAMBAA", "county_id" => 22],
            ["name" => "KABETE", "county_id" => 22],
            ["name" => "JUJA", "county_id" => 22],
            ["name" => "TURKANA CENTRAL", "county_id" => 23],
            ["name" => "TURKANA NORTH", "county_id" => 23],
            ["name" => "LOIMA", "county_id" => 23],
            ["name" => "TURKANA SOUTH", "county_id" => 23],
            ["name" => "TURKANA EAST", "county_id" => 23],
            ["name" => "TURKANA WEST", "county_id" => 23],
            ["name" => "KIBISH", "county_id" => 23],
            ["name" => "WEST POKOT", "county_id" => 24],
            ["name" => "POKOT CENTRAL", "county_id" => 24],
            ["name" => "POKOT SOUTH", "county_id" => 24],
            ["name" => "POKOT NORTH", "county_id" => 24],
            ["name" => "KIPKOMO", "county_id" => 24],
            ["name" => "SAMBURU EAST", "county_id" => 25],
            ["name" => "SAMBURU NORTH", "county_id" => 25],
            ["name" => "SAMBURU CENTRAL", "county_id" => 25],
            ["name" => "TRANS NZOIA WEST", "county_id" => 26],
            ["name" => "TRANS NZOIA EAST", "county_id" => 26],
            ["name" => "KWANZA", "county_id" => 26],
            ["name" => "KIMININI", "county_id" => 26],
            ["name" => "ENDEBESS", "county_id" => 26],
            ["name" => "SOY", "county_id" => 27],
            ["name" => "KAPSARET", "county_id" => 27],
            ["name" => "MOIBEN", "county_id" => 27],
            ["name" => "TURBO", "county_id" => 27],
            ["name" => "AINABKOI", "county_id" => 27],
            ["name" => "KESSES", "county_id" => 27],
            ["name" => "KEIYO NORTH", "county_id" => 28],
            ["name" => "MARAKWET WEST", "county_id" => 28],
            ["name" => "MARAKWET EAST", "county_id" => 28],
            ["name" => "KEIYO SOUTH", "county_id" => 28],
            ["name" => "NANDI CENTRAL", "county_id" => 29],
            ["name" => "NANDI NORTH", "county_id" => 29],
            ["name" => "NANDI EAST", "county_id" => 29],
            ["name" => "NANDI SOUTH", "county_id" => 29],
            ["name" => "TINDERET", "county_id" => 29],
            ["name" => "CHESUMEI", "county_id" => 29],
            ["name" => "BARINGO CENTRAL", "county_id" => 30],
            ["name" => "BARINGO NORTH", "county_id" => 30],
            ["name" => "KOIBATEK", "county_id" => 30],
            ["name" => "EAST POKOT", "county_id" => 30],
            ["name" => "MARIGAT", "county_id" => 30],
            ["name" => "MOGOTIO", "county_id" => 30],
            ["name" => "LAIKIPIA EAST", "county_id" => 31],
            ["name" => "LAIKIPIA NORTH", "county_id" => 31],
            ["name" => "LAIKIPIA CENTRAL", "county_id" => 31],
            ["name" => "NYAHURURU", "county_id" => 31],
            ["name" => "LAIKIPIA WEST", "county_id" => 31],
            ["name" => "NAKURU EAST", "county_id" => 32],
            ["name" => "RONGAI", "county_id" => 32],
            ["name" => "NAIVASHA", "county_id" => 32],
            ["name" => "GILGIL", "county_id" => 32],
            ["name" => "KURESOI NORTH", "county_id" => 32],
            ["name" => "NAKURU NORTH", "county_id" => 32],
            ["name" => "SUBUKIA", "county_id" => 32],
            ["name" => "NJORO", "county_id" => 32],
            ["name" => "MOLO", "county_id" => 32],
            ["name" => "KURESOI SOUTH", "county_id" => 32],
            ["name" => "NAKURU WEST", "county_id" => 32],
            ["name" => "NAROK NORTH", "county_id" => 33],
            ["name" => "NAROK SOUTH", "county_id" => 33],
            ["name" => "TRANSMARA EAST", "county_id" => 33],
            ["name" => "TRANSMARA WEST", "county_id" => 33],
            ["name" => "NAROK EAST", "county_id" => 33],
            ["name" => "NAROK WEST", "county_id" => 33],
            ["name" => "KAJIADO CENTRAL", "county_id" => 34],
            ["name" => "KAJIADO WEST", "county_id" => 34],
            ["name" => "KAJIADO NORTH", "county_id" => 34],
            ["name" => "LOITOKTOK", "county_id" => 34],
            ["name" => "ISINYA", "county_id" => 34],
            ["name" => "MASHURU", "county_id" => 34],
            ["name" => "KERICHO EAST", "county_id" => 35],
            ["name" => "BELGUT", "county_id" => 35],
            ["name" => "LONDIANI", "county_id" => 35],
            ["name" => "BURETI", "county_id" => 35],
            ["name" => "KIPKELION", "county_id" => 35],
            ["name" => "SIGOWET/SOIN", "county_id" => 35],
            ["name" => "BOMET CENTRAL", "county_id" => 36],
            ["name" => "SOTIK", "county_id" => 36],
            ["name" => "CHEPALUNGU", "county_id" => 36],
            ["name" => "KONOIN", "county_id" => 36],
            ["name" => "BOMET EAST", "county_id" => 36],
            ["name" => "KAKAMEGA CENTRAL", "county_id" => 37],
            ["name" => "KAKAMEGA NORTH", "county_id" => 37],
            ["name" => "KAKAMEGA SOUTH", "county_id" => 37],
            ["name" => "KAKAMEGA EAST", "county_id" => 37],
            ["name" => "MUMIAS WEST", "county_id" => 37],
            ["name" => "BUTERE", "county_id" => 37],
            ["name" => "KHWISERO", "county_id" => 37],
            ["name" => "LUGARI", "county_id" => 37],
            ["name" => "LIKUYANI", "county_id" => 37],
            ["name" => "MATETE", "county_id" => 37],
            ["name" => "MATUNGU", "county_id" => 37],
            ["name" => "NAVAKHOLO", "county_id" => 37],
            ["name" => "MUMIAS EAST", "county_id" => 37],
            ["name" => "VIHIGA", "county_id" => 38],
            ["name" => "SABATIA", "county_id" => 38],
            ["name" => "EMUHAYA", "county_id" => 38],
            ["name" => "HAMISI", "county_id" => 38],
            ["name" => "LUANDA", "county_id" => 38],
            ["name" => "BUNGOMA NORTH", "county_id" => 39],
            ["name" => "KIMILILI", "county_id" => 39],
            ["name" => "BUNGOMA SOUTH", "county_id" => 39],
            ["name" => "BUNGOMA CENTRAL", "county_id" => 39],
            ["name" => "BUNGOMA WEST", "county_id" => 39],
            ["name" => "BUNGOMA EAST", "county_id" => 39],
            ["name" => "BUMULA", "county_id" => 39],
            ["name" => "MT.ELGON", "county_id" => 39],
            ["name" => "CHEPTAIS", "county_id" => 39],
            ["name" => "WEBUYE WEST", "county_id" => 39],
            ["name" => "BUSIA", "county_id" => 40],
            ["name" => "BUTULA", "county_id" => 40],
            ["name" => "SAMIA", "county_id" => 40],
            ["name" => "BUNYALA", "county_id" => 40],
            ["name" => "NAMBALE", "county_id" => 40],
            ["name" => "TESO NORTH", "county_id" => 40],
            ["name" => "TESO SOUTH", "county_id" => 40],
            ["name" => "BUNYALA", "county_id" => 40],
            ["name" => "SIAYA", "county_id" => 41],
            ["name" => "BONDO", "county_id" => 41],
            ["name" => "UGENYA", "county_id" => 41],
            ["name" => "GEM", "county_id" => 41],
            ["name" => "UGUNJA", "county_id" => 41],
            ["name" => "RARIEDA", "county_id" => 41],
            ["name" => "BONDO", "county_id" => 41],
            ["name" => "GEM", "county_id" => 41],
            ["name" => "KISUMU EAST", "county_id" => 42],
            ["name" => "KISUMU WEST", "county_id" => 42],
            ["name" => "SEME", "county_id" => 42],
            ["name" => "NYANDO", "county_id" => 42],
            ["name" => "MUHORONI", "county_id" => 42],
            ["name" => "NYAKACH", "county_id" => 42],
            ["name" => "KISUMU CENTRAL", "county_id" => 42],
            ["name" => "HOMABAY", "county_id" => 43],
            ["name" => "NDHIWA", "county_id" => 43],
            ["name" => "RACHUONYO SOUTH", "county_id" => 43],
            ["name" => "RACHUONYO NORTH", "county_id" => 43],
            ["name" => "SUBA", "county_id" => 43],
            ["name" => "MBITA", "county_id" => 43],
            ["name" => "RACHUONYO EAST", "county_id" => 43],
            ["name" => "SUNA EAST", "county_id" => 44],
            ["name" => "KURIA WEST", "county_id" => 44],
            ["name" => "RONGO", "county_id" => 44],
            ["name" => "URIRI", "county_id" => 44],
            ["name" => "KURIA EAST", "county_id" => 44],
            ["name" => "AWENDO", "county_id" => 44],
            ["name" => "NYATIKE", "county_id" => 44],
            ["name" => "SUNA WEST", "county_id" => 44],
            ["name" => "KISII CENTRAL", "county_id" => 45],
            ["name" => "MASABA SOUTH", "county_id" => 45],
            ["name" => "KISII SOUTH", "county_id" => 45],
            ["name" => "GUCHA", "county_id" => 45],
            ["name" => "NYAMACHE", "county_id" => 45],
            ["name" => "KENYENYA", "county_id" => 45],
            ["name" => "GUCHA SOUTH", "county_id" => 45],
            ["name" => "SAMETA", "county_id" => 45],
            ["name" => "MARANI", "county_id" => 45],
            ["name" => "KITUTU CENTRAL", "county_id" => 45],
            ["name" => "NYAMIRA NORTH", "county_id" => 46],
            ["name" => "BORABU", "county_id" => 46],
            ["name" => "MANGA", "county_id" => 46],
            ["name" => "MASABA NORTH", "county_id" => 46],
            ["name" => "NYAMIRA SOUTH", "county_id" => 46],
            ["name" => "STAREHE", "county_id" => 47],
            ["name" => "WESTLANDS", "county_id" => 47],
            ["name" => "LANGATA", "county_id" => 47],
            ["name" => "KASARANI", "county_id" => 47],
            ["name" => "DAGORETTI", "county_id" => 47],
            ["name" => "EMBAKASI", "county_id" => 47],
            ["name" => "MAKADARA", "county_id" => 47],
            ["name" => "NJIRU", "county_id" => 47],
            ["name" => "KAMUKUNJI", "county_id" => 47],
            ["name" => "KIBRA", "county_id" => 47],
            ["name" => "MATHARE", "county_id" => 47],
        ];

        $seen = [];

        foreach ($subcounties as $subcounty) {
            // Normalize key by county + name (trim + uppercase to avoid tiny text differences)
            $key = $subcounty['county_id'] . '|' . strtoupper(trim($subcounty['name']));

            // If we've already inserted this (county_id, name), skip it
            if (isset($seen[$key])) {
                continue;
            }

            $seen[$key] = true;

            DB::table('subcounties')->updateOrInsert(
                [
                    'county_id' => $subcounty['county_id'],
                    'name'      => $subcounty['name'],
                ],
                [
                    'code'       => null,
                    'slug'       => Str::slug($subcounty['name']),
                    'updated_at' => now(),
                    'created_at' => now(),
                ]
            );
        }
    }
}

